### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by mowgli** [lwf/puppet-remote_file#26]
I use puppet 3.7.2 (yes, I know, old...) with the simple script:
```
  remote_file {
    '/tmp/http.html':
      ensure => present,
      source => 'https:/www.heise.de/';
  }
```

That leads to:
```
Error: Could not set 'present' on ensure: no implicit conversion of nil into String at 42:/etc/puppet/environments/test/modules/test/manifests/init.pp
Error: Could not set 'present' on ensure: no implicit conversion of nil into String at 42:/etc/puppet/environments/test/modules/test/manifests/init.pp
Wrapped exception:
no implicit conversion of nil into String
```

Any way to fix that?

**Comment by lwf** [comment]
Hi, thanks for the report. This module is largely unmaintained as I've moved on to greener pastures (read: container deployments, Kubernetes) and from what I understand Puppet now supports this as part of the File resource in 4.x. I'll accept PRs/patches if you feel inclined to debug it.

**Comment by reidmv** [comment]
@mowgli I just updated the module to 2.0.0, and as a result of those changes the oldest version of Puppet supported is 4.6.0.

I noticed in your example that your source URL is malformed; it's missing a slash character.

```
Is        'https:/www.heise.de/'
Should be 'https://www.heise.de/'
```

Is that maybe part of the problem?

If it's not but you still want to figure out what is going wrong, you can add `--trace` to your Puppet command and it will tell you what file and line number in Ruby code the error is coming from. That's the next piece of information we'd need to debug.

Because Puppet 3 is no longer supported and I'm closing this issue for now. If you do want to investigate it yourself I'd be happy to comment or try and provide pointers though. Feel free to add more information here if you'd like!
